apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: {{ .Values.upstream.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.app }}
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      nodePort: 30009