apiVersion: v1
kind: Secret
metadata:
  name: pg-secret
  namespace: default
type: Opaque
stringData:
  username: postgres
  superUserPassword: postgresSuperUserPsw
  replicationUserPassword: postgresReplicaPsw