apiVersion: v2
name: nginx
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
keywords:
  - nginx
  - LB
home: https://github.com/misanthropicat/postgres-fastapi-helm
maintainers:
  - name: Olga Mogish
    url: https://github.com/misanthropicat