apiVersion: v1
kind: Pod
metadata:
  name: "{{.Values.container.name.master}}"
  labels:
    name: "{{.Values.container.name.master}}"
spec:
  restartPolicy: {{default "Never" .Values.restartPolicy}}
  containers:
  - name: "{{.Values.container.name.master}}"
    image: "{{.Values.image}}"
    ports:
      - containerPort: {{.Values.container.port}}
        protocol: TCP
    envFrom:
      - configMapRef:
          name: pgmaster-config
    env:
      - name: POSTGRES_USERNAME
        valueFrom:
          secretKeyRef:
            name: pgmaster-secret
            key: username
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: pgmaster-secret
            key: password
    resources:
      requests:
        cpu: {{.Values.resources.cpu}}
        memory: {{.Values.resources.memory}}
    volumeMounts:
    - mountPath: /pgdata
      name: pgdata
    - mountPath: /backup
      name: backup
      readOnly: true
    - mountPath: /pguser
      name: pguser-volume
    - mountPath: /pgmaster
      name: pgmaster-volume
  volumes:
  - emptyDir: {}
    name: pgdata
  - emptyDir: {}
    name: backup
  - name: pguser-volume
    secret:
     secretName: pguser-secret
  - name: pgmaster-volume
    secret:
     secretName: pgmaster-secret