apiVersion: v1
kind: Service
metadata:
  name: "{{.Values.container.name.master}}"
  labels:
    name: "{{.Values.container.name.master}}"
spec:
  type: "{{.Values.serviceType}}"
  ports:
  - port: {{.Values.container.port}}
    targetPort: {{.Values.container.port}}
    protocol: TCP
    name: postgres
  selector:
    name: "{{.Values.container.name.master}}"