apiVersion: v2
name: ingress
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
keywords:
  - ingress
  - nginx
  - api-gateway
home: https://github.com/misanthropicat/postgres-fastapi-helm
maintainers:
  - name: Olga Mogish
    url: https://github.com/misanthropicat
dependencies:
  - name: nginx-ingress
    version: 1.36.0
    repository: https://charts.helm.sh/stable