ingress:
  name: ingress-service
  replicaCount: 1
  annotations: 
    class: nginx
  hosts:
    - host: example.local
      paths: 
        - path: /
          pathType: Prefix
          backend:
            serviceName: webapp
            servicePort: 80
  defaultBackend: webapp