webapp:
  name: webapp
  group: webapp
  replicaCount: 1
  container:
    image: olgamogish/postgres-fastapi-helm:latest
    imagePullPolicy: IfNotPresent
    port: 8000
  service:
    type: ClusterIP
    port: 8080