webapp:
  name: webapp
  group: webapp
  replicaCount: 1
  container:
    image: olgamogish/postgres-fastapi-helm:latest
    imagePullPolicy: Always
    port: 8080
  service:
    type: ClusterIP
    port: 8080
  config:
    name: webapp-config
  secret:
    name: webapp-secret